version: '3.8'

# volumes:
#   datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      #- MYSQL_DBNAME=
    ports:
      - 8081:80
      - 8083:443
    depends_on:
      - mysql


# version: '3.8'
# services:
#   php-apache-environment:
#     container_name: php-apache
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - db  
#     volumes:
#       - ./php/src:/var/www/html/
#     ports:
#       -8000:80
  
#   db:
#     container_name: db 
#     image: mysql 
#     restart: always
#     environment:
#       - MYSQL_DBHOST=mysql
#       - MYSQL_DBPORT=3306
#       - MYSQL_DBUSER=root
#       - MYSQL_DBPASS=secret
#     ports:
#       - "9906:3306"